#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.data-username=root
#spring.datasource.data-password=123456
#spring.datasource.url=jdbc:mysql://localhost:3306/testdb?characterEncoding=utf-8&useSSL=false
env=dev
user.named=zhagsan
user.age=90
